apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-tls
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways"]
  verbs: ["get"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-tls
  namespace: test
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-tls
subjects:
- kind: ServiceAccount
  name: ingress-tls
  namespace: test
roleRef:
  kind: ClusterRole
  name: ingress-tls
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: test
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-tls
  namespace: test
spec:
  selector:
    matchLabels:
      app: ingress-tls
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-tls
    spec:
      serviceAccountName: ingress-tls
      automountServiceAccountToken: true
      containers:
      - name: ingress-tls
        image: localhost:5000/ingress-tls:tst45
        args:
          - --issuer
          - namespaced:step-issuer
          - --kind
          - StepClusterIssuer
          - --group
          - certmanager.step.sm
          - -t
          - test/https-redirect
          - -f
          - /tls
          - -c
          - tls.crt
          - -k
          - tls.key
        ports:
        - containerPort: 443
          name: ingress-tls
        volumeMounts:
        - name: tls
          mountPath: /tls
        env:
        - name: RUST_LOG
          value: DEBUG
        - name: RUST_BACKTRACE
          value: "1"
      volumes:
        - name: tls
          csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-name: step-issuer
              csi.cert-manager.io/issuer-kind: StepClusterIssuer
              csi.cert-manager.io/issuer-group: certmanager.step.sm
              csi.cert-manager.io/dns-names: ingress-tls.test.svc,ingress-tls.test.svc.cluster.local
              csi.cert-manager.io/duration: 24h
              csi.cert-manager.io/renew-before: 1h
              csi.cert-manager.io/fs-group: "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-tls
  namespace: test
spec:
  selector:
    app: ingress-tls
  type: ClusterIP
  ports:
  - name: ingress-tls
    protocol: TCP
    port: 443
    targetPort: ingress-tls
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: ingress-tls
  namespace: test
webhooks:
- name: "ingress-tls.magicloud.lan"
  rules:
  - apiGroups:   ["*"]
    apiVersions: ["*"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["ingresses", "gateways", "httproutes"]
    scope:       "*"
  clientConfig:
    service:
      namespace: "test"
      name: "ingress-tls"
      path: "/validate"
      port: 443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwRENDQVVxZ0F3SUJBZ0lSQUw5bUxNVnpXMStzTkpsTFlnY3hhN1F3Q2dZSUtvWkl6ajBFQXdJd01ERVMKTUJBR0ExVUVDaE1KVFdGbmFXTnNiM1ZrTVJvd0dBWURWUVFERXhGTllXZHBZMnh2ZFdRZ1VtOXZkQ0JEUVRBZQpGdzB5TlRFd01Ua3hNVE14TWpaYUZ3MHpOVEV3TVRjeE1UTXhNalphTURBeEVqQVFCZ05WQkFvVENVMWhaMmxqCmJHOTFaREVhTUJnR0ExVUVBeE1SVFdGbmFXTnNiM1ZrSUZKdmIzUWdRMEV3V1RBVEJnY3Foa2pPUFFJQkJnZ3EKaGtqT1BRTUJCd05DQUFUcVQxYjVUcEs5UUtnL3J2Z2REUEE3WnZLRWpEK1RaY201TURpY3l6cGNocnZVU1lubAorcDhaaUVULzdHSnpSdE5DQTVMQUkxL1I1UGc0UDM3bnpIcGlvMFV3UXpBT0JnTlZIUThCQWY4RUJBTUNBUVl3CkVnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQWRCZ05WSFE0RUZnUVVTMm9RTGVRMnlGZ2lVVTFuMElrRGRCd1kKcmhJd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFQdFdIYTFFaHVzbWRoZHgwWVJzaVRGSU1qZU9ZdFlqK05XYgpZOWM2eDRRYkFpQURqSTVPY3hZdkNqeFR3cU1ERlNwcVc4RUFSQWVwK2xRTkxDUzZzT2VUUlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
# ---
# apiVersion: admissionregistration.k8s.io/v1
# kind: MutatingWebhookConfiguration
# metadata:
#   name: ingress-tls
#   namespace: test
# webhooks:
# - name: "ingress-tls.magicloud.lan"
#   rules:
#   - apiGroups:   ["*"]
#     apiVersions: ["*"]
#     operations:  ["CREATE", "UPDATE"]
#     resources:   ["ingresses", "gateways", "httproutes"]
#     scope:       "*"
#   clientConfig:
#     service:
#       namespace: "test"
#       name: "ingress-tls"
#       path: "/mutate"
#       port: 443
#     caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwRENDQVVxZ0F3SUJBZ0lSQUw5bUxNVnpXMStzTkpsTFlnY3hhN1F3Q2dZSUtvWkl6ajBFQXdJd01ERVMKTUJBR0ExVUVDaE1KVFdGbmFXTnNiM1ZrTVJvd0dBWURWUVFERXhGTllXZHBZMnh2ZFdRZ1VtOXZkQ0JEUVRBZQpGdzB5TlRFd01Ua3hNVE14TWpaYUZ3MHpOVEV3TVRjeE1UTXhNalphTURBeEVqQVFCZ05WQkFvVENVMWhaMmxqCmJHOTFaREVhTUJnR0ExVUVBeE1SVFdGbmFXTnNiM1ZrSUZKdmIzUWdRMEV3V1RBVEJnY3Foa2pPUFFJQkJnZ3EKaGtqT1BRTUJCd05DQUFUcVQxYjVUcEs5UUtnL3J2Z2REUEE3WnZLRWpEK1RaY201TURpY3l6cGNocnZVU1lubAorcDhaaUVULzdHSnpSdE5DQTVMQUkxL1I1UGc0UDM3bnpIcGlvMFV3UXpBT0JnTlZIUThCQWY4RUJBTUNBUVl3CkVnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQWRCZ05WSFE0RUZnUVVTMm9RTGVRMnlGZ2lVVTFuMElrRGRCd1kKcmhJd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFQdFdIYTFFaHVzbWRoZHgwWVJzaVRGSU1qZU9ZdFlqK05XYgpZOWM2eDRRYkFpQURqSTVPY3hZdkNqeFR3cU1ERlNwcVc4RUFSQWVwK2xRTkxDUzZzT2VUUlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
#   admissionReviewVersions: ["v1"]
#   sideEffects: None
#   timeoutSeconds: 5
